### ISSUE TITLE
fatal error: Argument 2 passed to token_help() must be an instance of Symfony\Component\HttpFoundation\Request

### ISSUE THREAD

**Issue by amool** [larowlan/token#16]
Hello,

I've been trying to test pathauto module for Drupal 8 for which token module is a dependency. Hence I cloned this repo & installed it. But my Drupal site is dying with following error:

```
Recoverable fatal error: Argument 2 passed to token_help() must be an instance of Symfony\Component\HttpFoundation\Request, array given, called in H:\xampp\htdocs\d8_alpha\core\modules\system\lib\Drupal\system\Plugin\Block\SystemHelpBlock.php on line 104 and defined in token_help() (line 23 of modules\token\token.module).
```

**Comment by larowlan** [comment]
What version of core do you have?

**Comment by amool** [comment]
Hi, I'm using alpha 12 release.

**Comment by larowlan** [comment]
You will most likely need to update to the latest HEAD using git, hook_help
signature changed

On 13 June 2014 14:30, amool notifications@github.com wrote:

> Hi, I'm using alpha 12 release.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/larowlan/token/issues/16#issuecomment-45974946.

## 

Lee Rowlands
Senior Drupal Developer
PreviousNext
skype: larowlan
email: larowlan@previousnext.com.au

**Comment by robertoguzman** [comment]
i'm having the same error using alpha 13 release

**Comment by vijaycs85** [comment]
not anymore with current head. we can close this one.

**Comment by jibran** [comment]
Thanks for testing it @vijaycs85. I am missing you here at Amsterdam sprint.

**Comment by vijaycs85** [comment]
awww. I miss you all too :(
